### ISSUE TITLE
BE: Chore: Create Starter BE Rails Repo

### ISSUE THREAD

**Issue by jdmchugh111** [turingschool/turlink-be#6]
set up a `rails new turlink-be -T -d="postgresql" --api`, with basic gems setup, basic database (and adding /coverage to .gitignore)

**Comment by epintozzi** [comment]
I have assigned you both so that whoever has time to get to this first does it. If you pick up this ticket, make sure to remove the other person so no one is duplicating work.

**Comment by noahdurbin** [comment]
finished this but since it wasn't a PR there is no pull request to review. realized after I got started that I probably could have created a setup branch after I started. I can rework this if needed

**Comment by noahdurbin** [comment]
also want to check in with you James on database schema before we create the migrations

**Comment by epintozzi** [comment]
> also want to check in with you James on database schema before we create the migrations

I would go ahead and close this ticket and create a chore ticket per db table (users and links to start probably? maybe also tags?)

**Comment by jdmchugh111** [comment]
Sorry I missed all this (I'm east coast time so wasn't online this late last night). Thanks for getting this set up Noah! I think we can talk database migrations today, although I would like some feedback from @epintozzi about how she envisions tagging to work. Is it an empty field that you can assign any old tag you want? Is there a set of tags you can select from? We could also just fix forward in a few days and do the migrations for tags (and probably a joins table called LinkTags) once the frontend gets through the first two epics and we have a clearer sense of how a user might interact with the tagging feature
